from tokens import *
#This is just a list of all operators in GO! LOL too many
t_PLUS    = r'\+'
t_MINUS   = r'-'
t_TIMES   = r'\*'
t_DIVIDE  = r'/'
t_MOD     = r'%'
t_AMPERS  = r'&'
t_OR 	  = r'\|'
t_CARET   = r'\^'
t_LL      = r'<<'
t_GG	  = r'>>'
t_AMPCAR  = r'&\^'
t_PLUSEQ  = r'\+='
t_MINUSEQ = r'-='
t_TIMESEQ = r'\*='
t_DIVIDEEQ= r'/='
t_MODEQ   = r'%='
t_AMPEQ   = r'&='
t_OREQ    = r'\|='
t_CAREQ   = r'\^='
t_LLEQ    = r'<<='
t_GGEQ    = r'>>='
t_AMPCAREQ= r'&\^='
t_AMPAMP  = r'&&'
t_OROR    = r'\|\|'
t_LMINUS  = r'<-'
t_PLUSPLUS= r'\+\+'
t_MINUSMIN= r'--'
t_EQEQ    = r'=='
t_LESS    = r'<'
t_GREAT   = r'>'
t_EQUAL   = r'='
t_NOT     = r'!'
t_NOTEQ   = r'!='
t_LEQ     = r'<='
t_GEQ     = r'>='
t_COLONEQ = r':='
t_DDD	  = r'\.\.\.'
t_LPAREN  = r'\('
t_RPAREN  = r'\)'
t_LBRACK  = r'\['
t_RBRACK  = r'\]'
t_LBRACE  = r'\{'
t_RBRACE  = r'\}'
t_COMMA   = r'\,'
t_DOT     = r'\.'
t_SEMICOL = r'\;'
t_COLON   = r'\:'  